#!/bin/bash

mv demographics.pgdump demographics.pgdump.bak

pg_dump demographics > demographics.pgdump
cp demographics.pgdump demographics-archive.pgdump
bzip2 demographics-archive.pgdump
mv demographics-archive.pgdump.bz2 ~/Dropbox/demographics-archive.pgdump.bz2




