\set ON_ERROR_STOP true

CREATE ROLE demographics LOGIN NOCREATEDB NOCREATEROLE NOREPLICATION NOSUPERUSER ENCRYPTED PASSWORD 'demographics';
CREATE DATABASE demographics WITH OWNER demographics ENCODING='UTF8'
