CREATE TABLE traits (
  id      SERIAL PRIMARY KEY,
  rating  SMALLINT NOT NULL DEFAULT 0,
  name    TEXT NOT NULL
);

INSERT INTO traits (rating, name) VALUES
(-1, 'Absent-Minded'),
(1, 'Adventurous'),
(-1, 'Afraid of commitment'),
(1, 'Ambitious'),
(0, 'Animal lover'),
(1, 'Artistic'),
(1, 'Athletic'),
(-1, 'Bloodthirsty'),
(-1, 'Boring'),
(-1, 'Braggart'),
(1, 'Brave'),
(0, 'Brooding'),
(0, 'Cat person'),
(1, 'Charismatic'),
(-1, 'Childish'),
(1, 'Chivalrous'),
(-1, 'Clumsy'),
(-1, 'Compulsive gambler'),
(1, 'Conversationalist'),
(-1, 'Coward'),
(-1, 'Cruel'),
(-1, 'Crybaby'),
(1, 'Cultured'),
(-1, 'Cursed'),
(1, 'Daredevil'),
(1, 'Dedicated'),
(1, 'Disciplined'),
(-1, 'Dislikes children'),
(-1, 'Diva'),
(0, 'Dog person'),
(0, 'Dramatic'),
(0, 'Drawn to the sea'),
(0, 'Dreamer'),
(-1, 'Drunkard'),
(0, 'Earthy'),
(-1, 'Easily bored'),
(0, 'Easily impressed'),
(1, 'Easy going'),
(-1, 'Eccentric'),
(1, 'Eloquent'),
(1, 'Equestrian'),
(-1, 'Evil'),
(0, 'Excitable'),
(1, 'Family-oriented'),
(0, 'Flirty'),
(-1, 'Foolish'),
(1, 'Friendly'),
(1, 'Frugal'),
(1, 'Fun-loving'),
(1, 'Genius'),
(-1, 'Gloomy'),
(-1, 'Glutton'),
(1, 'Good'),
(1, 'Good sense of humor'),
(1, 'Great kisser'),
(-1, 'Greedy'),
(1, 'Green thumb'),
(-1, 'Grumpy'),
(1, 'Haggler'),
(1, 'Handy'),
(0, 'Hates the outdoors'),
(1, 'Hopeless romantic'),
(-1, 'Hot-headed'),
(-1, 'Hubristic'),
(-1, 'Humorless'),
(0, 'Hyperactive'),
(-1, 'Inappropriate'),
(-1, 'Insane'),
(-1, 'Insecure'),
(-1, 'Insomniac'),
(1, 'Irresistible'),
(1, 'Jokester'),
(-1, 'Kleptomaniac'),
(-1, 'Lazy'),
(-1, 'Licentious'),
(-1, 'Loner'),
(-1, 'Loser'),
(0, 'Loves the outdoors'),
(0, 'Loves water'),
(1, 'Lucky'),
(0, 'Materialistic'),
(-1, 'Mean spirited'),
(-1, 'Megalomaniac'),
(-1, 'Misanthrope'),
(-1, 'Mooch'),
(-1, 'Morose'),
(1, 'Natural performer'),
(1, 'Natural cook'),
(1, 'Natural leader'),
(1, 'Neat'),
(-1, 'Neurotic'),
(0, 'Night owl'),
(1, 'Nurturing'),
(1, 'Outgoing'),
(-1, 'Over-emotional'),
(-1, 'Paranoid'),
(1, 'Patient'),
(1, 'People pleaser'),
(1, 'Perceptive'),
(0, 'Perfectionist'),
(-1, 'Procrastinator'),
(1, 'Proper'),
(-1, 'Prudish'),
(-1, 'Puny'),
(-1, 'Rebellious'),
(-1, 'Rude'),
(-1, 'Ruffian'),
(0, 'Sailor'),
(1, 'Schmoozer'),
(1, 'Scholarly'),
(1, 'Seductive'),
(0, 'Shy'),
(-1, 'Sleaze'),
(-1, 'Slob'),
(-1, 'Snob'),
(1, 'Social butterfly'),
(-1, 'Socially awkward'),
(-1, 'Solitary'),
(0, 'Stubborn'),
(-1, 'Stupid'),
(1, 'Sweet talker'),
(-1, 'Uncouth'),
(-1, 'Unflirty'),
(0, 'Unforgiving'),
(-1, 'Unkempt'),
(-1, 'Unlucky'),
(-1, 'Unstable'),
(-1, 'Vain'),
(1, 'Virtuoso'),
(-1, 'Wanton'),
(1, 'Wise'),
(1, 'Witty'),
(-1, 'Worrywart');

CREATE TABLE person_traits (
  person_id  INTEGER NOT NULL,
  trait_id   INTEGER NOT NULL,
  PRIMARY KEY (person_id, trait_id),
  FOREIGN KEY (person_id) REFERENCES persons (id) ON DELETE CASCADE,
  FOREIGN KEY (trait_id) REFERENCES traits (id) ON DELETE CASCADE
);
