ALTER TABLE maternities ALTER CONSTRAINT fk_maternity_person DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE paternities ALTER CONSTRAINT fk_paternity_person DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE families ALTER CONSTRAINT fk_family_husband DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE families ALTER CONSTRAINT fk_family_wife DEFERRABLE INITIALLY DEFERRED;
